name: Daily Cron Job
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Daily Cron Job
        run: |
          curl --request GET \
          --url '${{ secrets.WEBSITE_URL }}/api/cron' \
          --header 'x-api-key: ${{ secrets.CRON_API_KEY }}'
